year_date1 = int(input("Enter the year for date 1: "))
month_date1 = int(input("Enter the month for date 1: "))
day_date1 = int(input("Enter the day for date 1: "))
year_date2 = int(input("Enter the year for date 2: "))
month_date2 = int(input("Enter the month for date 2: "))
day_date2 = int(input("Enter the day for date 2: "))
m = (year_date1 * 360) + ((month_date1 -1) * 30) + (day_date1)
n = (year_date2 * 360) + ((month_date2 -1) * 30) + (day_date2)
a = abs(m - n)
print(f"The difference between {month_date1}/{day_date1}/{year_date1} and {month_date2}/{day_date2}/{year_date2} is {a} days!")